import Head from "next/head";
import { AddButton, DeleteButton } from "~/components/urlShortener/MutationButton";

import { api } from "~/utils/api";

export default function Home() {
  const shortUrls = api.shortUrls.getAll.useQuery(undefined, {
    refetchOnWindowFocus: false,
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-background __variable_a64ecd theme-gray min-h-screen font-sans antialiased">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-6xl text-white">Welcome to tRPC</h1>
          <AddButton />
          <ul className="text-2xl text-white">
            {shortUrls.data ? (
              <>
                {shortUrls.data.map((shortUrl) => {
                  return (
                    <li key={shortUrl.code}>
                      {shortUrl.code} {"->"} {shortUrl.url}
                      <DeleteButton uid={shortUrl.uid} />
                    </li>
                  );
                })}
              </>
            ) : (
              "Loading tRPC query..."
            )}
          </ul>
        </div>
      </main>
    </>
  );
}
